title: ClojureBridge Community Docs
email: info@clojurebridge.org
baseurl: /community-docs
twitter_username: ClojureBridgeSP
github_username:  ClojureBridgeSP
url: "http://clojurebridgesp.github.io/"
encoding: UTF-8

gems:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

relative_permalinks: false
port: 4444
